version : 2.1

orbs:
  node: circleci/node@4.7.0
  heroku: circleci/heroku@1.2.6

workflows:
  on_commit:
    jobs:
      - test_and_build
      - deploy:
          requires:
            - "test_and_build"
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                -main
    jobs:
      - test_and_build
      - deploy:
          requires:
            - "test_and_build"
          filters:
            branches:
              only:
              - main


jobs:
  test_and_build:
    docker:
      - image: circleci/node:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Build app
          command: yarn build
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - heroku/deploy-via-git:
          force: true
          