version : 2.1

orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  on_commit:
    jobs:
      - test_and_build
      - deploy:
          requires:
            - "test_and_build"
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                -main

jobs:
  test_and_build:
    docker:
      - image: circleci/node:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: npm install --force
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Build app
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - "."
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deplot-via-git:
          force: true
          