
version : 2.1

workflows:
  test:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/node:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test